print("                                          .,,,.           ")
print("                                       ,doodd;           ")
print("                                       'ooldd;           ")
print("                                        .:ddc    .','..  ")
print("    ..'.                                 'cc'  .coooool, ")
print("   ,loool'                                     ;ol;.'col ")
print("  .lxl;ldc.                                    ,oo, ,loc ")
print("   ':cldl'    .,,'.                   ..',,,.   .'.;ol:. ")
print("     :oo;    ;loxdl:,..............',;codxxol,    ,llo'  ")
print("     ':;.   ,loKWNKkdollooooooooolldxk0XWMWKol,   ;oll'  ")
print("           .clOWMMMMNXKXXXXXXXXXXKKXWMMMMMMWOlc.   ...   ")
print("          .:lxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdl:         ")
print("         .:loKMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0xcl,        ")
print("        .:ldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcdxlcl:.      ")
print("        :ldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xdkKKkol,     ")
print("       ,coKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxo0W0ol,    ")
print("      .:lkWMMMMMXOkXMMWNXKXNWMMWNKXWMMMMMMMMMNdoXWOlc.   ")
print("     .;lcOWMMMMM0ll0MNkc;;;ld0WNx:oXMMMMMMMMMW0ONMKlc.   ")
print("   .;coooxKWMMMMWNNNKKOoc:cdk0K0KKXWMMMMMXOxxk0NWWOlc.   ")
print("  .cld0XNNNWMMMMMMMNkdxkkkkkkxdONMMMMMMMMNKK0Odd0Xdl;    ")
print("  ;ldXX0OO0XWMMMMMMMWN0OkkkO0KNMMMMMMMMMWXKKXNNklocc,    ")
print(" .clkWKOkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkkkKWXoool:    ")
print("  ;loKWXKKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00KNW0lkOlc.   ")
print("  .;loOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNOoxNXoc;   ")
print("    'cccxXMMK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xx0WMWOlc.  ")
print("     ,llKWMWxoXMWNXWMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMXol;  ")
print("    .clxNMMWklKMXdxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklc. ")
print("    ,loKMMMM0lkWKlxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoc' ")
print("   .clkWMMMMWxoKNxl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXol; ")
print("   'll0MMMMMMNxo0Xxo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXol; ")
print("   'll0MMMMMMMNOdxxldNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0ll' ")
print("   .:lxNMMMMMXOKX0kOXWMMMMMMMMMMMMMMWNNWMMMMMMMMMMMXdl:. ")
print("    .clxXWMMMXkxxxOXWMMMMMMMMMMWXOkkxx0WMMMMMMMMMW0ol:.  ")
print("     .:lox0XNWWWX0kdodkkkkkkkkxodkO0KNMMMMMMWNX0kdoc'    ")
print("       .,;cloxxkkkkdlc:,;;;;;;ccokO0000OOkkkxdoc;,.      ")
print("           ..'',,;,,,.        .',,;:::::;,,,'...         ")